"use client"; // Mark this component as a Client Component
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar'; // Import Sidebar as default


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata without exporting it
const metadata = {
  title: "The Healthcare Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          <Sidebar /> {/* Add Sidebar */}
          <div className="main-content flex-grow" style={{ marginLeft: '250px', marginTop: '64px' }}> {/* Main content area */}

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}