"use client";

import { QuestionsProvider } from '@/context/QuestionsContext';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata without exporting it
const metadata = {
  title: "The Healthcare Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QuestionsProvider>
        <div className="flex">
            <Sidebar />
            <div className="main-content flex-grow" style={{ marginLeft: '250px', marginTop: '64px' }}>
            {children}
          </div>
        </div>
        </QuestionsProvider>
      </body>
    </html>
  );
}